version: "3.9"
services:
  web:
    build: .
    environment:
          - ASPNETCORE_URLS=http://*:7557
    ports:
      - "7557:7557"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "H3ngelo2020!"
      ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"